In [1]:
from __future__ import print_function
import matplotlib.pyplot as plt
import numpy as np
import os
import sys
import tarfile
from IPython.display import display, Image
from sklearn.linear_model import LogisticRegression
from six.moves.urllib.request import urlretrieve
from six.moves import cPickle as pickle

import pandas as pd
import openpyxl
import xgboost as xgb
from sklearn import metrics
import sklearn
import shap
import seaborn as sns
import random
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [9]:
data_num = 267
feature_num = 44

features = np.zeros((data_num,feature_num))
label = np.zeros((data_num,))

In [10]:
data_location = os.getcwd()+"/../../1.original/real_6_HT/spectf_train.xlsx"
raw_data = openpyxl.load_workbook(data_location)
raw_data = raw_data.active

In [11]:
for data_index in range(80):
    label[data_index] = raw_data.cell(row=data_index+1, column=1).value
    
    for feature_index in range(feature_num):
        features[data_index,feature_index]=raw_data.cell(row=data_index+1, column=2+feature_index).value

In [12]:
data_location = os.getcwd()+"/../../1.original/real_9_HT/spectf_test.xlsx"
raw_data = openpyxl.load_workbook(data_location)
raw_data = raw_data.active

In [13]:
for data_index in range(187):
    label[data_index+80] = raw_data.cell(row=data_index+1, column=1).value
    
    for feature_index in range(feature_num):
        features[data_index+80,feature_index]=raw_data.cell(row=data_index+1, column=2+feature_index).value

In [14]:
print(features)

[[59. 52. 70. ... 74. 64. 67.]
 [72. 62. 69. ... 71. 56. 58.]
 [71. 62. 70. ... 41. 51. 46.]
 ...
 [75. 73. 72. ... 75. 67. 71.]
 [59. 62. 72. ... 76. 70. 70.]
 [64. 66. 68. ... 64. 57. 54.]]


In [16]:
print(label)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0.]


In [17]:
scaler = MinMaxScaler()
scaler.fit(features)
features = scaler.transform(features)

In [18]:
np.save("features.npy",features)
np.save("label.npy",label)